---
- name: "batch 5 tickets"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 5
        delay: 0
  rules:
    - name: batch 5 tickets
      condition: event.i is defined
      action:
        run_job_template:
          name: "ServiceNow"
          organization: Default