---
- name: "Create SN ticket when code is pushed"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 120
        delay: 1  # 120 seconds
  rules:
    - name: Create SN ticket when code is pushed
      condition: event.payload is defined
      action:
        run_job_template:
          name: "ServiceNow"
          organization: Default