---
- name: "Execute Demo Job per 1 min"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 60
        delay: 1  # 60 seconds
  rules:
    - name: One minute of events rule
      condition: >-
        event.i in [
          0, 10, 20, 30, 40, 50, 59
        ]
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: Default