---
- name: EDA
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: "{{ kafka_host }}"
        port: 9092
        topic: "{{ kafka_topic }}"
  rules:
    - name: event is defined
      condition: event.body is defined
      action:
        run_job_template:
          name: "{{ job_template_name }}"
          organization: Default


