---
- name: EDA
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: ec2-3-142-189-167.us-east-2.compute.amazonaws.com
        port: 9092
        topic: "eda-playground"
  rules:
    - name: event is defined
      condition: event.body is defined
      action:
        run_playbook:
          name: "provision_aws_ec2_playbook.yml"
