---
- name: "Fire 20 jobs per sec"
  hosts: all
  sources:
    - ansible.eda.range:
        start: 1
        end: 21
        delay: 0
  rules:
  - name: Trigger job template
    condition: event.i is defined
    action:  
      run_job_template:
        name: "Demo Job Template"
        organization: Default  
        job_args:
          extra_vars:
            event_id: "{{ event.i }}"
