---
- name: "20events per min"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 20
        delay: 0.05
      
  rules:
    - name: 20 events per min
      condition: event.i is defined

      action:
        run_job_template:
          name: "Demo Job Template"
          organization: Default
        debug:
          msg: "Event {{ event.i }} fired"
