---
- name: "Fire 20 jobs per sec"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 5
        delay: 1
  rules:
  - name: Trigger job template
    condition: event.i is defined
    action:  
      run_job_template:
        name: "Demo Job Template"
        organization: Default  
