---
- name: "Rule6"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 5
        delay: 1
  rules:
    - name: Rule1 debug event
      condition: event.payload is defined
      action:
        debug:
          msg: "Event {{ event.payload }} fired"
