---
- name: "Rule11"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 5
        delay: 1
  rules:
    - name: Rule 11 debug event
      condition: event.payload.name == "rule11"
      action:
        debug:
          msg: "Event rule 11 {{ event.payload }} fired"
