---
- name: "Rule14"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 60
        delay: 1  # 60 seconds
  rules:
    - name: Rule 14 debug event
      condition: event.payload.name == "rule14"
      action:
        debug:
          msg: "Event rule 14{{ event.payload}} triggered"
