---
- name: "Rule6"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 5
        delay: 1
  rules:
    - name: Rule 6 debug event
      condition: event.payload.name == "rule6"
      action:
        debug:
          msg: "Event rule 6 {{ event.payload }} fired"
