---
- name: "Rule13"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 5
        delay: 1
  rules:
    - name: Rule 13 Job event
      condition: event.payload.name == "rule13"
      action:
        run_job_template:
          name: "Job13"
          organization: Default
