---
- name: "Rule4"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 60
        delay: 1  # 60 seconds
  rules:
    - name: Rule 4 debug event
      condition: event.payload.name == "rule4"
      action:
        debug:
          msg: "Event rule 4 {{ event.payload }} triggered"
