---
- name: "Rule8"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        batch_count: 5
        delay: 1
  rules:
    - name: Rule 8 Job event
      condition: event.payload.name == "rule8"
      action:
        run_job_template:
          name: "Job8"
          organization: Default
