---
- name: "Rule9"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 60
        delay: 1  # 60 seconds
  rules:
    - name: Rule 9 debug event
      condition: event.payload.name == "rule9"
      action:
        debug:
          msg: "Event rule 9{{ event.payload }} triggered"
