- name: "6000 event rules"
  hosts: all
  sources:
    - ansible.eda.generic:
        loop_count: 6000
  rules:
    - name: One million events rule
      condition: event.payload is defined
      action:
        debug:
          msg: "Event {{ event.payload }} triggered"