---
- name: "20events per min"
  hosts: all
  sources:
    - ansible.eda.generic:
        create_index: i
        payload:
          - name: '20events'

  rules:
    - name: Two minutes of events rule
      condition: event.payload is defined
      actions:
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
        - run_job_template:
            name: "ServiceNow"
            organization: Default
                            