---
- name: ServiceNow
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    PWD: '{{ SN_PASSWORD }}'
    JOB_TEMPLATE_URL: 
  tasks:
    - name: Debug extra var
      debug:
        msg: "Pwd is {{ PWD }}"
    - name: Create ServiceNow Change Request
      servicenow.itsm.change_request:
        instance:
          host: "dev281294"
          username: "admin"
          password:  "{{ PWD }}"
        type: normal
        priority: high
        risk: moderate
        other:
          approval: requested
        state: assess
        assignment_group: "CAB Approval"
        short_description: "ServiceNow"
        description: |
          Ana's test serviceNow
      register: new_change_request
    - name: Debug result
      debug:
        msg: "request is {{ new_change_request }}"
   